name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: download AS
      run: wget http://john.ccac.rwth-aachen.de:8000/ftp/as/source/c_version/asl-current.tar.gz
    
    - name: extract AS
      run: tar zxvf asl-current.tar.gz

    - name: copy defs file
      run: cd asl-current; cp Makefile.def-x86_64-unknown-linux Makefile.def

    - name: make AS
      run: cd asl-current; make


